version: "2"
services:
  gateway-mysql:
    image: "mysql:8.0.18"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gateway
      - MYSQL_USER=gateway
      - MYSQL_PASSWORD=gateway
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password

  products-mysql:
    image: "mysql:8.0.18"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=products
      - MYSQL_USER=products
      - MYSQL_PASSWORD=products
    ports:
      - 3307:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password

  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
